repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
    - id: docformatter
      language: python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-docstring-first
      stages:
      - commit
      - push
    - id: check-merge-conflict
      stages:
      - push
    - id: flake8
      stages:
      - commit
      - push
      args:
      - --max-line-length=120
    - id: trailing-whitespace
      stages:
      - commit
      - push
    - id: end-of-file-fixer
      stages:
      - commit
      - push
